spring:
  profiles:
    active: dev
  application:
    name: streama-cloud-admin
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:streama-cloud-admin-dev.yml?refreshEnabled=true

#  profiles:
#    active: dev
#  application:
#    name: streama-cloud-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
#        shared-configs:
#          - ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

admin:
  account: admin
  password: admin123

server:
  port: 7070

seata:
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
      username: "nacos"
      password: "nacos123"
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
      username: "nacos"
      password: "nacos123"
      ##if use MSE Nacos with auth, mutex with username/password attribute
      #access-key: ""
      #secret-key: ""
  service:
    vgroup-mapping:
      default_tx_group: default